# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curve.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(764, 554)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SmoothScrollArea = SmoothScrollArea(Frame)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 550))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.wellNameBar = SimpleCardWidget(self.scrollAreaWidgetContents)
        self.wellNameBar.setGeometry(QtCore.QRect(0, 0, 761, 41))
        self.wellNameBar.setObjectName("wellNameBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wellNameBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.wellName = SubtitleLabel(self.wellNameBar)
        self.wellName.setStyleSheet("FluentLabelBase {\n"
"    color: black;\n"
"}\n"
"\n"
"HyperlinkLabel {\n"
"    color: #009faa;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=true] {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"HyperlinkLabel[underline=false] {\n"
"    text-decoration: none;\n"
"}\n"
"\n"
"HyperlinkLabel:hover {\n"
"    color: #007780;\n"
"}\n"
"\n"
"HyperlinkLabel:pressed {\n"
"    color: #00a7b3;\n"
"}\n"
"FluentLabelBase{color:#000000}")
        self.wellName.setObjectName("wellName")
        self.horizontalLayout.addWidget(self.wellName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.curveTrackTop = CardWidget(self.scrollAreaWidgetContents)
        self.curveTrackTop.setGeometry(QtCore.QRect(30, 50, 161, 101))
        self.curveTrackTop.setObjectName("curveTrackTop")
        self.curveToolBar = CardWidget(self.curveTrackTop)
        self.curveToolBar.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.curveToolBar.setObjectName("curveToolBar")
        self.curveTitleBar = CardWidget(self.curveTrackTop)
        self.curveTitleBar.setGeometry(QtCore.QRect(0, 30, 161, 71))
        self.curveTitleBar.setObjectName("curveTitleBar")
        self.curveNameGroupBox = QtWidgets.QGroupBox(self.curveTitleBar)
        self.curveNameGroupBox.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.curveNameGroupBox.setStyleSheet("QGroupBox { border: none; }")
        self.curveNameGroupBox.setTitle("")
        self.curveNameGroupBox.setObjectName("curveNameGroupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.curveNameGroupBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.curveName = StrongBodyLabel(self.curveNameGroupBox)
        self.curveName.setObjectName("curveName")
        self.horizontalLayout_4.addWidget(self.curveName)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.theXRangeGroupBox = QtWidgets.QGroupBox(self.curveTitleBar)
        self.theXRangeGroupBox.setGeometry(QtCore.QRect(0, 30, 161, 44))
        self.theXRangeGroupBox.setTitle("")
        self.theXRangeGroupBox.setObjectName("theXRangeGroupBox")
        self.curveContent = CardWidget(self.scrollAreaWidgetContents)
        self.curveContent.setGeometry(QtCore.QRect(30, 150, 161, 341))
        self.curveContent.setObjectName("curveContent")
        self.depthTrackTop = CardWidget(self.scrollAreaWidgetContents)
        self.depthTrackTop.setGeometry(QtCore.QRect(440, 60, 161, 101))
        self.depthTrackTop.setObjectName("depthTrackTop")
        self.depthToolBar = CardWidget(self.depthTrackTop)
        self.depthToolBar.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.depthToolBar.setObjectName("depthToolBar")
        self.depthTitleBar = CardWidget(self.depthTrackTop)
        self.depthTitleBar.setGeometry(QtCore.QRect(0, 30, 161, 71))
        self.depthTitleBar.setObjectName("depthTitleBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.depthTitleBar)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.depthName = StrongBodyLabel(self.depthTitleBar)
        self.depthName.setObjectName("depthName")
        self.horizontalLayout_5.addWidget(self.depthName)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.depthContent = CardWidget(self.scrollAreaWidgetContents)
        self.depthContent.setGeometry(QtCore.QRect(440, 160, 161, 341))
        self.depthContent.setObjectName("depthContent")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.SmoothScrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.wellName.setText(_translate("Frame", "theWellName"))
        self.curveName.setText(_translate("Frame", "请选择曲线"))
        self.depthName.setText(_translate("Frame", "Depth"))
from qfluentwidgets import CardWidget, SimpleCardWidget, SmoothScrollArea, StrongBodyLabel, SubtitleLabel
