# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openWell.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_openWell(object):
    def setupUi(self, openWell):
        openWell.setObjectName("openWell")
        openWell.resize(613, 391)
        openWell.setStyleSheet("background-color: white;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(openWell)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchFrame = QtWidgets.QFrame(openWell)
        self.searchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wellNameSearch = StrongBodyLabel(self.searchFrame)
        self.wellNameSearch.setObjectName("wellNameSearch")
        self.horizontalLayout.addWidget(self.wellNameSearch)
        self.searchLineEdit = SearchLineEdit(self.searchFrame)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.verticalLayout_2.addWidget(self.searchFrame)
        self.tableFrame = QtWidgets.QFrame(openWell)
        self.tableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableFrame.setObjectName("tableFrame")
        self.verticalLayout_2.addWidget(self.tableFrame)

        self.retranslateUi(openWell)
        QtCore.QMetaObject.connectSlotsByName(openWell)

    def retranslateUi(self, openWell):
        _translate = QtCore.QCoreApplication.translate
        openWell.setWindowTitle(_translate("openWell", "Form"))
        self.wellNameSearch.setText(_translate("openWell", "井名搜索："))
from qfluentwidgets import CardWidget, SearchLineEdit, StrongBodyLabel
